<?php $block->renderFileLessToCss(); ?>
<header class="header-container">
<style type="text/css">
	.book-now{
		    float: left;
    		margin-left: -63px;
    		margin-top: 3px;
    		font-family: oswald,sans-serif;
    		font-weight: 500;
	}
	.book-now a {
     border: 2px solid;
     padding: 5px 20px 5px 20px;
     border-radius: 12px;
     font-weight: bolder;
}
.book-now a:hover {
    border: 2px solid;
    padding: 5px 20px 5px 20px;
    border-radius: 12px;
    font-weight: bolder;
    background: black;
    color: white;
}
.minicart-wrapper
{
	margin-left: 38px;
}
</style>
		<div class="header">
			<div class="h-left">
				<?php echo $this->getChildHtml("hozmegamenu_top"); ?>
				
			</div>
			<div class="h-right">
				<?php echo $this->getChildHtml("logo"); ?>
				
				<div class="absolute">
					<?php /*
					<div class="search-switcher">
						<?php echo $this->getChildHtml("top.search"); ?>
					</div>
					*/ ?>
					<div class="common">
					<div class="book-now">
					<a href="http://www.mytime.com/deals/CA/Studio-City/Health-&-Beauty/Sugaring/lay-bare-waxing-salon/211662-107219" target="_blank" id="mytime" class="" title="Book On MyTime">Book Now</a>
					</div>
					<?php /*
					<div class="link-hover">
						<p class="icon"></p>
						<div>
							<?php echo $this->getChildHtml("store_language"); ?>
							<div class="my-acount">
								<strong class="label"><span><?php echo __('My Account') ?></span></strong>
								<?php echo $this->getChildHtml("top.links"); ?>
							</div>
							<?php echo $this->getChildHtml("currency"); ?>
							
							
						</div>
					</div>
					*/?>
					<?php echo $this->getChildHtml("minicart");?>
					</div>
				</div>
			</div>
		</div>
		<div class="nav-ozmegamenu-inner">
			<div class="mobile-bar-icon"><span><?php /* @escapeNotVerified */ echo __('mobile icon'); ?></span></div>
		</div>
		<div class="mobile-bar-content">
			<div class ="mobile-bar-close"><?php /* @escapeNotVerified */ echo __('Close'); ?></div>
			<ul class = "tabs-mobile">
				<li class="item item-menu"><?php /* @escapeNotVerified */ echo __('Menu'); ?></li>
			</ul>
			<div class="tabs-content-mobile tabs-menu">
				<?php echo $this->getChildHtml("mobilemenu"); ?>
			</div>
		</div>
</header>
<script type="text/javascript">
require(["jquery"], function($){
	$(document).ready(function(){
		<!-- show, hide mobile bar content -->
		$(".mobile-bar-icon").click(function(){
			$(".mobile-bar-content").addClass("open");
		});
		$(".mobile-bar-close").click(function(){
			$(".mobile-bar-content").removeClass("open");
		});
	
	});
	$(window).scroll(function () {
	   if ($(this).scrollTop() > 0) {
		 $('.header-container').addClass("fix-header-container");
	   } else {
		$('.header-container').removeClass("fix-header-container");
	   }
	});
});

</script>